"""
engine/target_grammar_loader.py — reads data/target_grammar_drills.csv (one-
time batch-generated by scripts/generate_target_grammar_drills.py) and
lazily fills in the viewer's native-language translation.

Same idea as engine.session.LessonSession._fill_missing_translations for
CEFR-J Vocabulary, generalized: there the canonical column is always English
(source_en); here the canonical language is the topic's OWN target_lang
(Ukrainian sentences for a Ukrainian-aspect topic, Japanese for は/が...) —
so translate_phrase's from_lang has to vary per topic instead of being
hardcoded "English". Translations still go through the same
engine.gemini.translate_phrase + phrase_translations cache, so a phrase
translated for one student is free for the next.
"""
from __future__ import annotations

import csv
import random
from pathlib import Path

import pandas as pd
import streamlit as st

from engine import target_grammar_paths as _tgp

ROOT = Path(__file__).parent.parent
DRILLS_PATH = ROOT / "data" / "target_grammar_drills.csv"

# Mirrors engine.recommender.DIFFICULTY_TO_CEFR, inverted -- duplicated
# (rather than imported) so this module doesn't need engine.recommender
# (and its DATABASE_URL-requiring engine.db import) just to build a
# dataframe; both are small, hand-written constants unlikely to drift
# independently, same reasoning generate_target_grammar_drills.py used for
# its own LANG_TO_CODE copy.
_CEFR_TO_DIFFICULTY = {"A1": 1, "A2": 2, "B1": 3, "B2": 4, "C1": 5, "C2": 6}

# engine.loader.load_phrases()'s output shape -- keep in sync so
# pd.concat([real_df, synthetic_df]) lines up cleanly.
_GRAMMAR_DF_COLUMNS = [
    "lesson_id", "phrase_id", "difficulty", "native", "target",
    "topic_en", "topic_uk", "topic_es", "topic_ko", "topic_fr", "topic_de",
    "topic_ja", "topic_zh", "topic_pt", "topic_it", "topic_pl", "topic_ru",
    "topic_ca", "topic_nl",
]


def _load_all() -> list[dict]:
    if not DRILLS_PATH.exists():
        return []
    with open(DRILLS_PATH, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def load_topic_drills(target_lang: str, topic_key: str, native_lang: str, n: int = 5) -> list[dict]:
    """
    Up to `n` random sentences for this topic, each as {"native": ..., "target": ...}
    — the same shape session.phrases() / phase3_practice's other test types use.

    Free-tier fallback: translate_phrase is paid-gated (like everywhere else
    Gemini is optional) -- a free user just sees the target_lang sentence
    left in the "native" slot too (still usable, monolingual), same
    convention as LessonSession._fill_missing_translations.
    """
    rows = [
        r for r in _load_all()
        if r["lang"] == target_lang and r["topic_key"] == topic_key
    ]
    if not rows:
        return []
    random.shuffle(rows)
    rows = rows[:n]

    if native_lang == target_lang:
        return [{"native": r["sentence"], "target": r["sentence"]} for r in rows]

    from engine import gemini
    out = []
    for r in rows:
        target_text = r["sentence"]
        try:
            native_text = gemini.translate_phrase(target_text, target_lang, native_lang)
        except gemini.PaidFeatureRequired:
            native_text = target_text
        except Exception:
            native_text = target_text
        out.append({"native": native_text, "target": target_text})
    return out


@st.cache_data(show_spinner=False)
def build_grammar_lesson_rows(target_lang: str, native_lang: str) -> pd.DataFrame:
    """
    Synthetic Grammar-lesson rows for every engine.target_grammar_paths topic
    registered for target_lang -- shaped exactly like
    engine.loader.load_phrases()'s output (same columns, plus one extra
    "native_needs_translation" marker column) so grammar.py's "grammar"
    module loader can pd.concat() them onto the real
    imlls_database_with_titles.xlsx rows and the rest of the app (Category
    filter, Select Lesson dropdown, wave path, Phase 1-8 flow, mastery/SRS)
    needs no separate code path for them (2026-08-23, Natalia's request:
    "Ukrainian cases should show up inside the Nouns & Quantities category
    like any other lesson").

    Returns one row per (topic, generated sentence) -- up to 8 per topic, all
    of them (unlike engine.gemini's Phase-3 target_grammar drill picker,
    which only samples a random few per practice attempt; a real lesson
    should show the same fixed set every time, like every other Grammar
    lesson does). Empty dataframe if target_lang has no registered topics
    (e.g. target_lang == "English" -- its grammar is what the 182-lesson
    curriculum was built from in the first place) or none of them have been
    batch-generated yet (data/target_grammar_drills.csv missing/incomplete).

    Deliberately does NOT translate `native` here -- confirmed live
    (2026-08-23) that eagerly translating every topic's sentences to build
    just the *picker's* dataframe (up to 7 topics x 8 sentences = 56 live
    Gemini calls, sequentially, before the Category/Select Lesson dropdowns
    can even render) hung the Grammar setup page for well over a minute on
    a first-time language pair. `native` is left equal to `target` here
    (a valid, always-correct fallback -- picker.py's Category/Select Lesson
    labels only ever need topic_en, never this column) and
    "native_needs_translation" is set True; the actual translation happens
    lazily, bounded to just the ~8 rows of ONE lesson at a time -- either
    when engine/picker.py's lesson preview renders (only the currently
    selected lesson) or when engine.session.LessonSession opens it for real
    (same "translate only what's actually being shown" principle the
    CEFR-J Vocabulary module already uses, engine.session
    ._fill_missing_translations -- extended there to also cover this
    column instead of only its own source_en case).
    """
    topics = _tgp.paths_for_language(target_lang)
    if not topics:
        return pd.DataFrame(columns=_GRAMMAR_DF_COLUMNS + ["native_needs_translation"])

    all_rows = _load_all()

    rows = []
    for topic in topics:
        sentences = [
            r["sentence"] for r in all_rows
            if r["lang"] == target_lang and r["topic_key"] == topic["key"]
        ]
        if not sentences:
            continue  # not batch-generated yet -- skip, don't half-render a lesson
        topic_label = f"{topic['title']} ({topic['gloss_en']})"
        lesson_id = topic["lesson_id"]
        for i, target_text in enumerate(sentences[:8]):
            rows.append({
                "lesson_id":  lesson_id,
                "phrase_id":  lesson_id * 100 + i,   # outside imlls_database's 1-1454 range
                "difficulty": _CEFR_TO_DIFFICULTY.get(topic["level"], 1),
                "native":     target_text,   # placeholder -- see docstring; fixed lazily
                "target":     target_text,
                "topic_en":   topic_label,   # every other topic_XX left NaN -- get_grammar_topics()
                "native_needs_translation": native_lang != target_lang,
            })                               # already falls back to topic_en for every native_lang

    return pd.DataFrame(rows, columns=_GRAMMAR_DF_COLUMNS + ["native_needs_translation"])


def translate_rows_native(df: pd.DataFrame, target_lang: str, native_lang: str) -> pd.DataFrame:
    """
    Fill in real `native` text for rows built by build_grammar_lesson_rows
    with native_needs_translation=True -- called on a SMALL, already-sliced
    dataframe (one lesson's ~8 rows), never the whole picker dataframe. Rows
    without that column (every other Grammar lesson) or already resolved
    pass through untouched. Returns a new dataframe (caller's copy is not
    mutated).
    """
    if "native_needs_translation" not in df.columns:
        return df
    mask = df["native_needs_translation"] == True  # noqa: E712 (explicit vs NaN)
    if not mask.any():
        return df
    out = df.copy()
    from engine import gemini
    for idx in out.index[mask]:
        source_text = out.at[idx, "target"]
        try:
            out.at[idx, "native"] = gemini.translate_phrase(source_text, target_lang, native_lang)
        except gemini.PaidFeatureRequired:
            pass  # leave the target_text placeholder -- free tier, same fallback everywhere else
        except Exception:
            pass
    return out
