"""
engine/warmup_loader.py — reads data/warmup_questions.csv (one-time batch-
generated by scripts/generate_warmup_questions.py) and serves a random
pre-written question for a (target_lang, level) pair.

Phase 1 (Розминка) fires on every single lesson start — the single most
frequent live-Gemini call in the app before this (CLAUDE.md 2026-09-16).
Same "pre-generate once, translate lazily on read" pattern already used by
engine.target_grammar_loader / the CEFR-J Vocabulary module: the question
TEXT is batch-generated once per (target_lang, level) and free to serve
after that; only the native_lang translation for bilingual mode is still a
live (but cheap, cached) engine.gemini.translate_phrase call.
"""
from __future__ import annotations

import csv
import random
from pathlib import Path

ROOT = Path(__file__).parent.parent
QUESTIONS_PATH = ROOT / "data" / "warmup_questions.csv"


def _load_all() -> list[dict]:
    if not QUESTIONS_PATH.exists():
        return []
    with open(QUESTIONS_PATH, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def random_question(target_lang: str, level: str) -> str | None:
    """
    One random pre-generated question for this (target_lang, level), or
    None if the pool has nothing for it yet (not batch-generated, or an
    unrecognized level string) — caller falls back to live generation.
    """
    rows = [r for r in _load_all() if r["lang"] == target_lang and r["level"] == level]
    if not rows:
        return None
    return random.choice(rows)["question"]
