"""
scripts/generate_character_phrases.py — one-time (resumable) translation of
assets/characters/phrases.yaml's character names + motivational phrases into
every language in grammar.py's LANGUAGES list.

2026-09-07: only en/uk/es/ko had names+phrases hand-written; the other 10
target languages fell back to English (engine.characters._resolve_lang() has
no mapping for them at all), so every character bubble showed in English
regardless of native_lang for those students.

Unlike engine/i18n.py's UI strings, this content lives directly in the YAML
(no hand-written/generated split) — es/ko were already Gemini-generated too
per this project's established practice (data/i18n_generated.json is the
same: AI-generated, not native-verified), so new languages are written
straight into phrases.yaml the same way, not to a separate overlay file.

English and Ukrainian stay untouched (source + authoritative reference).
Every other language only fills in whatever it's missing, phrase-by-phrase,
matched by index against the English list (all languages currently have the
same phrase count per category, verified before running this).

Usage:
    python scripts/generate_character_phrases.py --limit 10 --lang French
        Small test batch on one language — sanity-check tone/quality first.

    python scripts/generate_character_phrases.py
        Full run, every language missing entries. Resumable: skips
        (lang, char, category, index) triples already present, and skips a
        character's name if already present for that language.

Requires GEMINI_API_KEY.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from engine import gemini
from engine.loader import LANG_COLUMNS

YAML_PATH = ROOT / "assets" / "characters" / "phrases.yaml"

_HEADER = (
    "# assets/characters/phrases.yaml\n"
    "# Character phrases, all 14 supported languages (2026-09-07 --\n"
    "# originally uk/en/es/ko only; the other 10 were generated by\n"
    "# scripts/generate_character_phrases.py, same AI-generated/not-\n"
    "# native-verified status as data/i18n_generated.json).\n"
    "# Language is picked automatically from session_state.launcher_native.\n"
)


def _dump(data: dict) -> None:
    """yaml.safe_load()/dump() round-trips fine but drops comments (not part
    of PyYAML's data model) -- reattach the file header every write so a
    resumed/interrupted run never silently loses it."""
    body = yaml.dump(data, allow_unicode=True, sort_keys=False, width=100)
    YAML_PATH.write_text(_HEADER + "\n" + body, encoding="utf-8")


_SKIP_LANGS = {"English", "Ukrainian"}

_CHARACTER_VOICE = {
    "natalia": "a warm, encouraging language tutor",
    "mark": "a chill, funny study buddy",
    "sophie": "an enthusiastic, upbeat cheerleader",
    "ai_bot": "a quirky, deadpan robot assistant",
    "polyglot": "a mysterious, wise, slightly theatrical polyglot legend",
}


def translate_name(name_en: str, character_key: str, target_lang: str) -> str:
    prompt = (
        f"This is the display name of a language-learning app's mascot "
        f"character ({_CHARACTER_VOICE.get(character_key, 'a character')}): "
        f"\"{name_en}\". Give the natural {target_lang} form a native "
        f"speaker would expect for this character name in that app -- "
        f"transliterate proper names into the target script if that's "
        f"the natural convention for that language (e.g. a Ukrainian or "
        f"Korean version of \"Sophie\" would be transliterated, not left "
        f"in Latin script), but translate/localize title-like names (e.g. "
        f"\"AI-Bot\", \"The Mysterious Polyglot\") the way a game or app "
        f"localization would. Return ONLY the name, nothing else, no quotes."
    )
    return gemini._model(gemini._LITE).generate_content(prompt).text.strip().strip('"')


def translate_phrase(phrase_en: str, character_key: str, category: str, target_lang: str) -> str:
    prompt = (
        f"Translate this line from a language-learning app's mascot "
        f"character into natural, colloquial {target_lang}. The character "
        f"is {_CHARACTER_VOICE.get(character_key, 'a friendly character')}, "
        f"speaking directly to the student in the \"{category}\" moment. "
        f"Keep every emoji and every {{placeholder}} (e.g. {{score}}, "
        f"{{corrections}}) exactly as they are, in the same position if "
        f"natural for the target language's word order. Match the tone -- "
        f"casual and warm, not stiffly formal. Return ONLY the translated "
        f"line, nothing else, no quotes.\n\nLine: {phrase_en}"
    )
    return gemini._model(gemini._LITE).generate_content(prompt).text.strip().strip('"')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None,
                         help="Max phrases to generate this run (across all languages).")
    parser.add_argument("--lang", default=None,
                         help="Only this language (full name, e.g. 'French').")
    args = parser.parse_args()

    data = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8"))

    target_names = [args.lang] if args.lang else [
        name for name in LANG_COLUMNS if name not in _SKIP_LANGS
    ]

    done = 0
    for name in target_names:
        code = LANG_COLUMNS[name]
        for char_key, char in data.items():
            # Name
            name_map = char.setdefault("name", {})
            if code not in name_map:
                en_name = name_map.get("en", char_key)
                try:
                    translated = translate_name(en_name, char_key, name)
                except Exception as e:
                    print(f"  FAILED name {code}:{char_key} ({e.__class__.__name__}: {e})")
                else:
                    name_map[code] = translated
                    done += 1
                    print(f"  name {code}:{char_key} -> {translated!r}")
                    _dump(data)
                    if args.limit and done >= args.limit:
                        print(f"Hit --limit {args.limit}, stopping.")
                        return

            # Phrases, per category
            for category, by_lang in char.get("phrases", {}).items():
                en_list = by_lang.get("en", [])
                existing = by_lang.get(code, [])
                if len(existing) >= len(en_list):
                    continue
                new_list = list(existing)
                for i in range(len(existing), len(en_list)):
                    try:
                        translated = translate_phrase(en_list[i], char_key, category, name)
                    except Exception as e:
                        print(f"  FAILED {code}:{char_key}:{category}[{i}] ({e.__class__.__name__}: {e})")
                        break
                    new_list.append(translated)
                    by_lang[code] = new_list
                    done += 1
                    print(f"  {code}:{char_key}:{category}[{i}] -> {translated!r}")
                    _dump(data)
                    if args.limit and done >= args.limit:
                        print(f"Hit --limit {args.limit}, stopping.")
                        return

    print(f"Done. Generated {done} new entries -> {YAML_PATH}")


if __name__ == "__main__":
    main()
