"""Generate language-specific verb rows (engine/verb_form_topics.py) into data/target_grammar_drills.csv.

Per language: 3 groups x 8 rows, each generated by one Gemini call, then a SECOND independent call
verifies/corrects every row (forms are easy to get subtly wrong). Resumable per topic_key.
Usage: python scripts/generate_verb_forms.py [--langs Spanish,French]
"""
import argparse, csv, json, sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine import gemini, verb_form_topics as vf  # noqa: E402

OUT = ROOT / "data" / "target_grammar_drills.csv"
CODES = {"Spanish": "es", "French": "fr", "German": "de", "Italian": "it", "Portuguese": "pt", "Catalan": "ca",
         "Dutch": "nl", "Swedish": "sv", "Romanian": "ro", "Russian": "ru", "Ukrainian": "uk", "Polish": "pl",
         "Czech": "cs", "Bulgarian": "bg", "Turkish": "tr", "Japanese": "ja", "Korean": "ko"}


def _ask(prompt):
    return gemini._parse_json(gemini._model(gemini._FLASH).generate_content(prompt).text, fallback=None)


def gen_group(lang, sp, g, n_groups, used):
    prompt = (f"Write a learner reference list in {lang}: exactly {vf.ROWS_PER_GROUP} rows, one per verb, using "
             f"{sp['what']}. "
             f"Each row has exactly three parts separated by ' - ' in this pattern: {sp['pattern']}. Example row: {sp['example']}\n"
             f"This is set {g} of {n_groups}: set 1 = the very most common verbs, later sets = next most common. "
             f"Do NOT reuse these verbs already used: {sorted(used) or 'none'}.\n"
             "All forms must be standard, correct and exactly as a native dictionary/grammar would give them. "
             'Return JSON only: an array of row strings.')
    rows = _ask(prompt)
    if not isinstance(rows, list): return None
    seen, uniq = set(used), []
    for r in rows:
        if not (isinstance(r, str) and r.count(" - ") == 2): continue
        inf = r.split(" - ")[0].strip()
        if inf in seen: continue          # same verb already used in an earlier group/row
        seen.add(inf); uniq.append(r.strip())
    return uniq[: vf.ROWS_PER_GROUP]


def verify(lang, sp, rows):
    numbered = "\n".join(f"{i}. {r}" for i, r in enumerate(rows))
    prompt = (f"You are a strict native {lang} grammarian. Each row must follow the pattern '{sp['pattern']}' "
             f"(example: {sp['example']}). Check EVERY form in EVERY row for correctness (spelling, stress/diacritics, "
             f"tense/person, aspect). Return JSON only: an array with one string per row, in order, with the row "
             f"corrected if anything was wrong, otherwise unchanged.\n{numbered}")
    res = _ask(prompt)
    if isinstance(res, list) and len(res) == len(rows) and all(isinstance(x, str) and x.count(" - ") == 2 for x in res):
        return [x.strip() for x in res]
    return rows


def run_lang(lang, done):
    sp, code, out, used = vf.SPECS[lang], CODES[lang], [], set()
    n_groups = sp.get("groups", vf.GROUPS)
    levels = sp.get("levels", vf.GROUP_LEVELS)
    for g in range(1, n_groups + 1):
        key = vf.topic_key(code, g)
        if key in done: continue
        for attempt in range(3):
            rows = gen_group(lang, sp, g, n_groups, used)
            if rows and len(rows) == vf.ROWS_PER_GROUP: break
        else:
            print("FAILED", lang, g, flush=True); continue
        rows = verify(lang, sp, rows)
        for r in rows: used.add(r.split(" - ")[0].strip())
        out += [(lang, key, levels[g - 1], r) for r in rows]
        print("ok", lang, g, rows[:2], flush=True)
    return out


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--langs", default=",".join(vf.SPECS)); a = ap.parse_args()
    done = set()
    if OUT.exists():
        with OUT.open(encoding="utf-8", newline="") as f: done = {r["topic_key"] for r in csv.DictReader(f)}
    with ThreadPoolExecutor(7) as ex:
        results = list(ex.map(lambda l: run_lang(l, done), a.langs.split(",")))
    rows = [r for res in results for r in res]
    with OUT.open("a", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\r\n")
        for r in rows: w.writerow(r)
    print("appended", len(rows), "rows")

if __name__ == "__main__":
    main()
